title: "Jessica Magno"  
logo: "/images/logojessicamagno.JPG?raw=true"  
description: >  
  Bioinformata desde 2019, atualmente em transição para a Ciência de Dados.  
  Formada pela UFPR, tenho experiência em análise de dados biológicos, modelagem estatística e machine learning aplicado.  
  Além da minha trajetória profissional, compartilho conteúdos sobre maternidade e tecnologia no Instagram [@datascientistmom](https://instagram.com/datascientistmom).  

  Esta página está em construção. Em breve, mais informações e projetos estarão disponíveis.  

  [View My LinkedIn Profile](https://www.linkedin.com/in/magnojessica/) | [View My Instagram Profile](https://instagram.com/datascientistmom/)  

remote_theme: "pages-themes/minimal@v0.2.0"  
plugins:  
  - jekyll-remote-theme  

google_analytics: "UA-000000-0" # Seu Google Analytics ID  
