title: "Jessica Magno"  
logo: "/images/logojessicamagno.JPG?raw=true"  
description: >  
  <br>
  Cientista de Dados e Bioinformata.  
  Formada pela UFPR, tenho experiência em análise de dados biológicos, modelagem estatística e machine learning aplicado.  
  <br><br>
  <a href="https://www.linkedin.com/in/magnojessica/">View my LinkedIn Profile</a> 
  
remote_theme: "pages-themes/minimal@v0.2.0"  
plugins:  
  - jekyll-remote-theme  
colors:
  crimson: '#900C3F'
